### ISSUE TITLE
App crashes when pics with >2mb file size is added to record

### ISSUE THREAD

**Issue by mcyusuf** [yuzumone/Recordachi#7]
When I try to make use of pictures with size >2mb in the record, the app crashes and won't open till I clear it's data.

**How to reproduce**
1. Click on the **+** icon
2. Input values for name and category
3. Tap on the blue area with gallery icon to add your preferred picture
4. Select a picture with file size >2mb
5. Tap the tick icon at the top right to save
6. App crashes.

Device: Tecno K7
OS: Android Nougat 7.0

**Recording of bug**
https://youtu.be/WbrUx2wSog0

**Logcat**
```
05-22 05:29:32.495 I/BufferQueueProducer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa7dde000,id:3589,api:1,p:8119,c:224) new GraphicBuffer needed
05-22 05:29:32.509 I/BufferQueueProducer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa7dde000,id:3589,api:1,p:8119,c:224) queueBuffer: fps=1.39 dur=1433.91 max=1406.29 min=27.62
05-22 05:29:34.308 I/BufferQueueProducer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa7dde000,id:3589,api:1,p:8119,c:224) queueBuffer: fps=18.34 dur=1799.72 max=1105.53 min=5.07
05-22 05:29:35.596 I/BufferQueueProducer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa7dde000,id:3589,api:1,p:8119,c:224) queueBuffer: fps=12.42 dur=1287.84 max=1024.06 min=16.73
05-22 05:29:35.613 I/LatinIme(908): onActivate() : EditorInfo = Package = net.yuzumone.recordachi : Type = Text : Learning = Enable : Suggestion = Show : AutoCorrection = Enable : Microphone = Show : Incognito = Disable
05-22 05:29:35.650 W/Conv2QueryExtension(908): Conv2Query not enabled due to current app [net.yuzumone.recordachi] not in whitelist
05-22 05:29:37.088 I/BufferQueueProducer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa7dde000,id:3589,api:1,p:8119,c:224) queueBuffer: fps=2.01 dur=1491.34 max=647.61 min=347.20
05-22 05:29:38.173 I/BufferQueueProducer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa7dde000,id:3589,api:1,p:8119,c:224) queueBuffer: fps=1.84 dur=1085.75 max=1001.41 min=84.35
05-22 05:29:39.175 I/BufferQueueProducer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa7dde000,id:3589,api:1,p:8119,c:224) queueBuffer: fps=1.00 dur=1001.57 max=1001.57 min=1001.57
05-22 05:29:40.176 I/BufferQueueProducer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa7dde000,id:3589,api:1,p:8119,c:224) queueBuffer: fps=1.00 dur=1001.59 max=1001.59 min=1001.59
05-22 05:29:41.178 I/BufferQueueProducer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa7dde000,id:3589,api:1,p:8119,c:224) queueBuffer: fps=27.97 dur=1001.24 max=439.84 min=15.85
05-22 05:29:41.979 I/LatinIme(908): onActivate() : EditorInfo = Package = net.yuzumone.recordachi : Type = Text : Learning = Enable : Suggestion = Show : AutoCorrection = Enable : Microphone = Show : Incognito = Disable
05-22 05:29:41.995 W/Conv2QueryExtension(908): Conv2Query not enabled due to current app [net.yuzumone.recordachi] not in whitelist
05-22 05:29:42.986 I/BufferQueueProducer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa7dde000,id:3589,api:1,p:8119,c:224) queueBuffer: fps=13.82 dur=1808.33 max=1015.65 min=15.91
05-22 05:29:44.758 I/BufferQueueProducer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa7dde000,id:3589,api:1,p:8119,c:224) queueBuffer: fps=2.26 dur=1772.13 max=998.91 min=210.46
05-22 05:29:45.758 I/BufferQueueProducer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa7dde000,id:3589,api:1,p:8119,c:224) queueBuffer: fps=1.00 dur=1000.03 max=1000.03 min=1000.03
05-22 05:29:46.759 I/BufferQueueProducer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa7dde000,id:3589,api:1,p:8119,c:224) queueBuffer: fps=1.00 dur=1000.36 max=1000.36 min=1000.36
05-22 05:29:47.042 W/PackageManager(803): checkPermission(): android.permission.READ_EXTERNAL_STORAGE of net.yuzumone.recordachi is denied.
05-22 05:29:47.101 I/PPS     (803): [PPSNotifyAppState] pack:net.yuzumone.recordachi, com:net.yuzumone.recordachi.MainActivity, state:0,ActiveCount = 1
05-22 05:29:47.101 I/PPS     (803): [PPSNotifyAppState] nPackNum:102, pack:net.yuzumone.recordachi, com:net.yuzumone.recordachi.MainActivity, state:0, pid:8119, last_boost_tid:8119
05-22 05:29:47.807 I/BufferQueueProducer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa7dde000,id:3589,api:1,p:8119,c:224) queueBuffer: fps=28.61 dur=1048.65 max=268.15 min=4.97
05-22 05:29:48.823 I/BufferQueueProducer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa7dde000,id:3589,api:1,p:8119,c:224) queueBuffer: fps=15.76 dur=1015.38 max=755.53 min=11.34
05-22 05:29:49.239 I/PPS     (803): [PPSNotifyAppState] pack:net.yuzumone.recordachi, com:net.yuzumone.recordachi.MainActivity, state:1,ActiveCount = 2
05-22 05:29:49.239 I/PPS     (803): [PPSNotifyAppState] nPackNum:102, pack:net.yuzumone.recordachi, com:net.yuzumone.recordachi.MainActivity, state:1, pid:8119, last_boost_tid:8119
05-22 05:29:49.240 I/libPerfService(803): [perfNotifyAppState] foreground:net.yuzumone.recordachi, pid:8119
05-22 05:29:49.403 I/PPS     (803): [PPSNotifyAppState] pack:net.yuzumone.recordachi, com:net.yuzumone.recordachi.MainActivity, state:0,ActiveCount = 1
05-22 05:29:49.403 I/PPS     (803): [PPSNotifyAppState] nPackNum:102, pack:net.yuzumone.recordachi, com:net.yuzumone.recordachi.MainActivity, state:0, pid:8119, last_boost_tid:8119
05-22 05:29:49.493 I/BufferQueueProducer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa7dde000,id:3589,api:1,p:-1,c:224) disconnect(P): api 1
05-22 05:29:49.494 I/BufferQueueConsumer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa7dde000,id:3589,api:1,p:-1,c:224) getReleasedBuffers: returning mask 0xffffffffffffffff
05-22 05:29:50.399 I/WindowManager(803): Destroying surface Surface(name=net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2137 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:948 com.android.server.wm.WindowState.destroyOrSaveSurface:2113 com.android.server.wm.WindowManagerService.tryStartExitingAnimation:3245 com.android.server.wm.WindowManagerService.relayoutWindow:3125 com.android.server.wm.Session.relayout:227 android.view.IWindowSession$Stub.onTransact:286 com.android.server.wm.Session.onTransact:148 
05-22 05:29:50.415 I/BufferQueueConsumer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa7dde000,id:3589,api:1,p:-1,c:-1) disconnect(C)
05-22 05:29:50.415 I/BufferQueue(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa7dde000,id:3589,api:1,p:-1,c:-1) ~BufferQueueCore
05-22 05:30:49.897 I/libPerfService(803): [perfNotifyAppState] foreground:net.yuzumone.recordachi, pid:8119
05-22 05:30:49.897 I/PPS     (803): [PPSNotifyAppState] pack:net.yuzumone.recordachi, com:net.yuzumone.recordachi.MainActivity, state:1,ActiveCount = 2
05-22 05:30:49.898 I/PPS     (803): [PPSNotifyAppState] nPackNum:102, pack:net.yuzumone.recordachi, com:net.yuzumone.recordachi.MainActivity, state:1, pid:8119, last_boost_tid:8119
05-22 05:30:50.289 I/BufferQueueConsumer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa4427000,id:3594,api:0,p:-1,c:224) setConsumerName: net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity
05-22 05:30:50.289 I/BufferQueueConsumer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa4427000,id:3594,api:0,p:-1,c:224) setDefaultBufferSize: width=720 height=1280
05-22 05:30:50.333 I/BufferQueueProducer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa4427000,id:3594,api:1,p:8119,c:224) connect(P): api=1 producer=(8119:net.yuzumone.recordachi) producerControlledByApp=true
05-22 05:30:50.347 I/BufferQueueProducer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa4427000,id:3594,api:1,p:8119,c:224) setMaxDequeuedBufferCount: maxDequeuedBuffers = 3
05-22 05:30:50.355 I/BufferQueueProducer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa4427000,id:3594,api:1,p:8119,c:224) new GraphicBuffer needed
05-22 05:30:50.450 I/BufferQueueProducer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa4427000,id:3594,api:1,p:8119,c:224) new GraphicBuffer needed
05-22 05:30:51.414 I/BufferQueueProducer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa4427000,id:3594,api:1,p:8119,c:224) new GraphicBuffer needed
05-22 05:30:51.425 I/BufferQueueProducer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa4427000,id:3594,api:1,p:8119,c:224) queueBuffer: fps=1.96 dur=1021.87 max=962.31 min=59.57
05-22 05:30:52.492 I/BufferQueueProducer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa4427000,id:3594,api:1,p:8119,c:224) queueBuffer: fps=16.86 dur=1067.56 max=469.97 min=17.11
05-22 05:30:56.033 I/BufferQueueProducer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa4427000,id:3594,api:1,p:8119,c:224) queueBuffer: fps=0.28 dur=3540.84 max=3540.84 min=3540.84
05-22 05:30:56.327 E/AndroidRuntime(8119): Process: net.yuzumone.recordachi, PID: 8119
05-22 05:30:56.327 E/AndroidRuntime(8119): 	at net.yuzumone.recordachi.db.d$5.a(Unknown Source)
05-22 05:30:56.327 E/AndroidRuntime(8119): 	at net.yuzumone.recordachi.db.d$5.compute(Unknown Source)
05-22 05:30:56.333 W/ActivityManager(803):   Force finishing activity net.yuzumone.recordachi/.MainActivity
05-22 05:30:56.381 I/PPS     (803): [PPSNotifyAppState] pack:net.yuzumone.recordachi, com:net.yuzumone.recordachi.MainActivity, state:0,ActiveCount = 1
05-22 05:30:56.381 I/PPS     (803): [PPSNotifyAppState] nPackNum:102, pack:net.yuzumone.recordachi, com:net.yuzumone.recordachi.MainActivity, state:0, pid:8119, last_boost_tid:8119
05-22 05:30:56.386 I/AEE_AED (8371): [preset_info] pid: 8119, tid: -1361051648, name: UNKNOWN  >>> net.yuzumone.recordachi <<<
05-22 05:30:56.588 I/BufferQueueConsumer(224): [Application Error: net.yuzumone.recordachi](this:0xa7dde000,id:3596,api:0,p:-1,c:224) setConsumerName: Application Error: net.yuzumone.recordachi
05-22 05:30:56.588 I/BufferQueueConsumer(224): [Application Error: net.yuzumone.recordachi](this:0xa7dde000,id:3596,api:0,p:-1,c:224) setDefaultBufferSize: width=129 height=129
05-22 05:30:56.599 I/BufferQueueConsumer(224): [Application Error: net.yuzumone.recordachi](this:0xa7dde000,id:3596,api:0,p:-1,c:224) setDefaultBufferSize: width=812 height=512
05-22 05:30:56.613 I/BufferQueueProducer(224): [Application Error: net.yuzumone.recordachi](this:0xa7dde000,id:3596,api:1,p:803,c:224) connect(P): api=1 producer=(803:system_server) producerControlledByApp=false
05-22 05:30:56.628 I/BufferQueueProducer(224): [Application Error: net.yuzumone.recordachi](this:0xa7dde000,id:3596,api:1,p:803,c:224) setMaxDequeuedBufferCount: maxDequeuedBuffers = 3
05-22 05:30:56.642 I/BufferQueueProducer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa4427000,id:3594,api:1,p:-1,c:224) disconnect(P): api 1
05-22 05:30:56.642 I/BufferQueueProducer(224): [Application Error: net.yuzumone.recordachi](this:0xa7dde000,id:3596,api:1,p:803,c:224) new GraphicBuffer needed
05-22 05:30:56.642 I/BufferQueueConsumer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa4427000,id:3594,api:1,p:-1,c:224) getReleasedBuffers: returning mask 0xffffffffffffffff
05-22 05:30:56.676 I/BufferQueueProducer(224): [Application Error: net.yuzumone.recordachi](this:0xa7dde000,id:3596,api:1,p:803,c:224) new GraphicBuffer needed
05-22 05:30:57.056 I/BufferQueueProducer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa4427000,id:3594,api:1,p:-1,c:224) disconnect(P): api -1
05-22 05:30:57.065 I/WindowManager(803): Destroying surface Surface(name=net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2137 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:948 com.android.server.wm.WindowState.removeLocked:1469 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2678 com.android.server.wm.AppWindowToken.destroySurfaces:374 com.android.server.wm.WindowStateAnimator.finishExit:586 com.android.server.wm.AppWindowAnimator.stepAnimationLocked:435 com.android.server.wm.WindowAnimator.updateAppWindowsLocked:204 
05-22 05:30:57.073 I/BufferQueueConsumer(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa4427000,id:3594,api:1,p:-1,c:-1) disconnect(C)
05-22 05:30:57.074 I/BufferQueue(224): [net.yuzumone.recordachi/net.yuzumone.recordachi.MainActivity](this:0xa4427000,id:3594,api:1,p:-1,c:-1) ~BufferQueueCore
05-22 05:31:00.141 I/ActivityManager(803): Killing 8119:net.yuzumone.recordachi/u0a221 (adj 902): crash
05-22 05:31:00.148 I/BufferQueueProducer(224): [Application Error: net.yuzumone.recordachi](this:0xa7dde000,id:3596,api:1,p:-1,c:224) disconnect(P): api 1
05-22 05:31:00.149 I/BufferQueueConsumer(224): [Application Error: net.yuzumone.recordachi](this:0xa7dde000,id:3596,api:1,p:-1,c:224) getReleasedBuffers: returning mask 0xffffffffffffffff
05-22 05:31:00.188 W/ViewRootImpl[recordachi](803): Dropping event due to root view being removed: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=397.42303, y[0]=526.22015, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=1, eventTime=88430584, downTime=88430565, deviceId=2, source=0x1002 }
05-22 05:31:00.222 I/WindowManager(803): Destroying surface Surface(name=Application Error: net.yuzumone.recordachi) called by com.android.server.wm.WindowStateAnimator.destroySurface:2137 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:948 com.android.server.wm.WindowState.destroyOrSaveSurface:2113 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementInner:434 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop:235 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement:183 com.android.server.wm.WindowManagerService$H.handleMessage:8464 android.os.Handler.dispatchMessage:110 
05-22 05:31:00.236 I/BufferQueueConsumer(224): [Application Error: net.yuzumone.recordachi](this:0xa7dde000,id:3596,api:1,p:-1,c:-1) disconnect(C)
05-22 05:31:00.236 I/BufferQueue(224): [Application Error: net.yuzumone.recordachi](this:0xa7dde000,id:3596,api:1,p:-1,c:-1) ~BufferQueueCore
```

**Comment by yuzumone** [comment]
Are you installed the APK of v1.0.0? This version has a crash issue when adding record. I fixed already by #3. I will soon release the bug fixed version APK.

**Comment by mcyusuf** [comment]
Okay, would be expecting the fixed all version.

**Comment by tobias-g1** [comment]
This hasn't been resolved on the latest version of the application, using the steps above it still occurs so was likely a different error that you resolved. 

*Replicated on Android 8, Application Version 1.0.1*

```
   --------- beginning of crash
05-23 19:31:27.608 21264-21280/net.yuzumone.recordachi E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
    Process: net.yuzumone.recordachi, PID: 21264
    java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
        at android.database.CursorWindow.nativeGetString(Native Method)
        at android.database.CursorWindow.getString(CursorWindow.java:438)
        at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
        at net.yuzumone.recordachi.db.d$5.a(Unknown Source:101)
        at net.yuzumone.recordachi.db.d$5.compute(Unknown Source:0)
        at android.arch.lifecycle.ComputableLiveData$2.run(Unknown Source:31)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
05-23 19:31:27.641 21264-21283/net.yuzumone.recordachi E/CursorWindow: Failed to read row 0, column 0 from a CursorWindow which has 0 rows, 4 columns.
```

**Comment by yuzumone** [comment]
I have confirmed that images with 8mb is able to register on my device (NuAns Neo Reloaded, Android 7.1.2). In this app, images larger than 1024px are resized. Possibly, in the case of the image you were selecting, the file size after resizing may still be large to save in the database. Would you please provide the image file you seleteced.

**Comment by tobias-g1** [comment]
This was the image I used in my testing:

https://upload.wikimedia.org/wikipedia/commons/f/ff/Pizigani_1367_Chart_10MB.jpg

**Comment by yuzumone** [comment]
It was caused by the large file size even after resizing. I will implement to check the file size and change it to resize. Thank you!
